name: Deploy MkDocs (uv)
on:
  push: { branches: [ main ] }
permissions: { contents: write }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with: { enable-cache: true }
      - run: uv python install
      - run: uv sync --locked || uv sync
      - run: uv run mkdocs gh-deploy --force
